# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
warnings_are_errors: false
addons:
  apt:
    update: true
    packages:
      - libfftw3-3
      - libfftw3-dev
      - libsndfile1
      - libsndfile1-dev
r_packages:
  - covr
cache:
  packages: true
env:
  global:
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
after_success:
  - Rscript -e 'library(covr); codecov()'